# For more information: https://laravel.com/docs/sail
version: "3.5"
services:
  laravel.test:
    container_name: "laravel-docker"
    build:
        context: ./
        dockerfile: Dockerfile
        args:
          WWWGROUP: "${WWWGROUP:-1000}"
    image: laravel/docker
    networks:
      - "my_network"
networks:
  my_network:
    driver: bridge
volumes:
  app_volume:
    driver: local